[project]
name = "flickr-scraper"
version = "1.0.0"
description = "A tool for scraping images from Flickr"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cyclopts>=3.4.0",
    "flickrapi>=2.4.0",
    "inference-sdk>=0.30.0",
    "loguru>=0.7.3",
    "ratelimit>=2.2.1",
]
